# shadenet_config.yaml

model:
  mid_layers: [64, 128, 256, 512, 512]
  n_classes: 1

training:
  EPOCHS: 100
  warmup_epochs: 8
  lr: 0.00007
  ignore_index: 255
  dice_w: 0.3
  mask_w: 0.3
  perceptual_w: 0.2
  mse_w: 0.6
  accumulation_steps: 2
  device: cuda
  save_dir: ./checkpoints
  
traingenerator:
  root: ./Dataset/ISTD_Dataset/train
  augment: true
  isTrain: true

valgenerator:
  root: ./Dataset/ISTD_Dataset/test
  augment: false
  isTrain: false
  
dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  
transforms:
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  img_resize: [640, 480]
  mask_resize: [640, 480] 